//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1_cmd.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp1_cmd.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Backup Canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackupCanceled {
            get {
                return ResourceManager.GetString("BackupCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_Exit {
            get {
                return ResourceManager.GetString("BTN_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transfer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BTN_Transfer {
            get {
                return ResourceManager.GetString("BTN_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue Transfer ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueTransfer {
            get {
                return ResourceManager.GetString("ContinueTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DiskFreeSize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DiskFreeSize {
            get {
                return ResourceManager.GetString("DiskFreeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DiskRequireSize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DiskRequireSize {
            get {
                return ResourceManager.GetString("DiskRequireSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DiskSpaceError に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DiskSpaceError {
            get {
                return ResourceManager.GetString("DiskSpaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup data missmatch. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_BACKUP_DATA_MISSMATCH {
            get {
                return ResourceManager.GetString("Error_BACKUP_DATA_MISSMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FTP account error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_FTP_ACCOUNT_ERROR {
            get {
                return ResourceManager.GetString("Error_FTP_ACCOUNT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FTP server error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_FTP_SERVER_ERROR {
            get {
                return ResourceManager.GetString("Error_FTP_SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FTP transfer error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_FTP_TRANSFER_ERROR {
            get {
                return ResourceManager.GetString("Error_FTP_TRANSFER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LCU connection error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_LCU_CONNECT_ERROR {
            get {
                return ResourceManager.GetString("Error_LCU_CONNECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LCU Create folder fail. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_LCU_CREATE_FOLDER_ERROR {
            get {
                return ResourceManager.GetString("Error_LCU_CREATE_FOLDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LCU disk Info error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_LCU_DISK_INFO_ERROR {
            get {
                return ResourceManager.GetString("Error_LCU_DISK_INFO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LCU File download error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_LCU_DOWNLOAD_ERROR {
            get {
                return ResourceManager.GetString("Error_LCU_DOWNLOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to get line information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_LCU_LINEINFO_ERROR {
            get {
                return ResourceManager.GetString("Error_LCU_LINEINFO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LCU update disk full. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_LCU_UPDATE_DISK_FULL {
            get {
                return ResourceManager.GetString("Error_LCU_UPDATE_DISK_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LCU FTP Upload Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_LCU_UPLOAD_ERROR {
            get {
                return ResourceManager.GetString("Error_LCU_UPLOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LCU WebApi Command Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_LCU_WEBAPI_ERROR {
            get {
                return ResourceManager.GetString("Error_LCU_WEBAPI_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation completed successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_OK {
            get {
                return ResourceManager.GetString("Error_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disk Space Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_UPDATE_DISKSPACE_ERROR {
            get {
                return ResourceManager.GetString("Error_UPDATE_DISKSPACE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UpdateData not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_UPDATE_READ_ERROR {
            get {
                return ResourceManager.GetString("Error_UPDATE_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to get line information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetLineInfoError {
            get {
                return ResourceManager.GetString("GetLineInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Disk Space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_CheckDiskSpace {
            get {
                return ResourceManager.GetString("MENU_CheckDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ConnectionCheck に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_ConnectionCheck {
            get {
                return ResourceManager.GetString("MENU_ConnectionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_File {
            get {
                return ResourceManager.GetString("MENU_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read UpdateData に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_ReadUpdateData {
            get {
                return ResourceManager.GetString("MENU_ReadUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modules Transfer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModulesTransfer {
            get {
                return ResourceManager.GetString("ModulesTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No target machine selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoTargetMachine {
            get {
                return ResourceManager.GetString("NoTargetMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not enough disk space for update. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotEnoughDiskSpace {
            get {
                return ResourceManager.GetString("NotEnoughDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no units to update. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoUnitToUpdate {
            get {
                return ResourceManager.GetString("NoUnitToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuestionTransferStart {
            get {
                return ResourceManager.GetString("QuestionTransferStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit Application? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuitAppMsg {
            get {
                return ResourceManager.GetString("QuitAppMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Transfer ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuitTransferMsg {
            get {
                return ResourceManager.GetString("QuitTransferMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading Update Info... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReadingUnitInfo {
            get {
                return ResourceManager.GetString("ReadingUnitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read Line information ...&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReadLineInformation {
            get {
                return ResourceManager.GetString("ReadLineInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select Update machine. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetSelect {
            get {
                return ResourceManager.GetString("TargetSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Transfer information? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransferInformation {
            get {
                return ResourceManager.GetString("TransferInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnitSoftTransferTool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
